### ISSUE TITLE
Could not cmake successfully on either Ubuntu or MacOS

### ISSUE THREAD

**Issue by windclearup** [ultrapre/Stellarium-mobile#1]
Hi there, I tried to build the project with cmake on Ubuntu 14.04.5 LTS,
sudo apt-get install qtbase5-dev qtdeclarative5-dev
cd Stellarium-mobile
mkdir build
cd build
cmake ..
while got the error below:
------------------------------------
CMake Error at CMakeLists.txt:246 (FIND_PACKAGE):
  By not providing "FindQt5Declarative.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5Declarative", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Declarative"
  with any of the following names:

    Qt5DeclarativeConfig.cmake
    qt5declarative-config.cmake

  Add the installation prefix of "Qt5Declarative" to CMAKE_PREFIX_PATH or set
  "Qt5Declarative_DIR" to a directory containing one of the above files.  If
  "Qt5Declarative" provides a separate development package or SDK, be sure it
  has been installed.

-- Configuring incomplete, errors occurred!
------------------------------------

I also tried to build it on MacOS 10.15.4, while got the similar error:
brew install qt5
mkdir debug
cd debug
cmake ..
------------------------------------
-- Found Clang 11.0
CMake Warning (dev) at /usr/local/Cellar/qt/5.15.1/lib/cmake/Qt5Core/Qt5CoreMacros.cmake:44 (message):
  qt5_use_modules is not part of the official API, and might be removed in Qt
  6.
Call Stack (most recent call first):
  /usr/local/Cellar/qt/5.15.1/lib/cmake/Qt5Core/Qt5CoreMacros.cmake:431 (_qt5_warn_deprecated)
  src/CMakeLists.txt:321 (QT5_USE_MODULES)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find Qt5Declarative (missing: Qt5Declarative_DIR)
CMake Error at /usr/local/Cellar/qt/5.15.1/lib/cmake/Qt5Core/Qt5CoreMacros.cmake:451 (message):
  Cannot use "Declarative" module which has not yet been found.
Call Stack (most recent call first):
  src/CMakeLists.txt:321 (QT5_USE_MODULES)

-- Configuring incomplete, errors occurred!
------------------------------------

It seems caused by missing of Qt5Declarative, while I've already installed  qtdeclarative5-dev on Ubuntu.
So can you share how to solve this build error, thanks a lot!

**Comment by ultrapre** [comment]
please try the env recommended in https://github.com/ultrapre/Stellarium-mobile/releases/tag/v1.29.6

and open .pro file rather than cmake with qtcreator.
It seems to be the Qt version problem, since I also meet same building bugs.

**Comment by windclearup** [comment]
build success with QtCreator.
