### ISSUE TITLE
Publish Stellarium-mobile version 23.2 via tag "v23.2" rather than "v0.23.2"

### ISSUE THREAD

**Issue by vog** [ultrapre/Stellarium-mobile#7]
I installed Stellarium-mobile using Obtainium.

Obtainium installed it correctly from tag "v0.23.2". Alas, the application in the APK reports itself as version "23.2" rather than "0.23.2", so Obtainium always shows it as "upgradable" to me.

Would it be possible to publish version "23.2" again, with a different tag "v23.2" rather than "v0.23.2"?

That would make it work smoother with Obtainium, and would be a more consistent naming anyways.

**Comment by ultrapre** [comment]
Thank you!
